language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
    allow_failures:
        - php: 5.3

env:
  matrix:
    - ES_COMPOSER_NODEV=no
    - ES_COMPOSER_NODEV=yes

install:
  - /bin/bash ansible/provision.sh

before_script:
  - mkdir -p build/logs
  - echo "extension=memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - if [ $ES_COMPOSER_NODEV == "no" ] && ! $(php -v | head -1 | grep -q 'PHP 5.3'); then sudo composer require "guzzlehttp/guzzle" "4.2.*" --dev --no-ansi --no-progress --no-interaction; fi

script:
  - phpunit -c test/phpunit-travis.xml

after_script:
  - cat /var/log/elasticsearch/*.log
  - cat /var/log/nginx/*.log
  - cat build/logs/phpunit-tap.log
  - sudo composer require satooshi/php-coveralls --no-ansi --no-progress --no-interaction
  - php vendor/bin/coveralls -v
